version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pendaftaran_db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend-dashboard
    container_name: frontend-app
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql-data: