POST http://localhost:3000/api/pendaftaran

Content-Type: application/json
{
  "nik": "1234567890123456",
  "nama": "Riski",
  "noHp": "081234567890",
  "provinsi": "Jawa Barat",
  "kabupaten": "Bandung",
  "kecamatan": "Cibiru",
  "kelurahan": "Palasari"
}
